### PR TITLE
Add custom query_string_normalizer for HTTParty get requests

### PR DESCRIPTION
**Pull request by momer**
Current AdRoll API spec requires lists to be sent in the format `?param=PARAM1,PARAM2`. The previous version of this gem would send a hasherized version of the query string as in HTTParty spec (not compatible with current AdRoll API).

### CODE REVIEW

**Comment by dustinsgoodman** [comment]
What do you mean by hasherized? Not fully sure if I understand the problem here. Our system uses most of the available methods various levels of data complexity and we haven't had an issue yet which is why this PR confuses me a bit. Trying to understand what you're looking for exactly.

**Comment by momer** [comment]
On mobile, so I'll provide a more detailed response when I get to a computer.

If, for example, one uses the 'Report#ad' method with multiple ad eids, HTTParty will parameterize them in the format of the [default normalizer](https://github.com/jnunemaker/httparty/blob/247d541f93e27d96e8226ec222a0c488886d1017/lib/httparty.rb#L129) e.g. '/selected_ids[]=1&selected_ids[]=2&selected_ids[]=3'. If the rails normalized is disabled, this query still doesn't produce the requisite '?param=item,item2,item3' format. 

I discovered this bug while using some methods provided by adroller with multiple campaign/ad eids; the result of which ended up not filtering my query as expected. 

After some research and debugging of the output parameterization from HTTParty in the gen, I'd come to a this resolution, which resolved my issues. Again, I compared the gem http requests to the API spec/docs, and that's what led me down this path.

Hope that provides some clarity!

**Comment by dustinsgoodman** [comment]
That makes perfect sense! I guess we don't do operations like that so it hasn't bit us yet. A bit shocking that AdRoll doesn't handle params correctly but that's not our problem. Good find and good solution! 👍

**Comment by dustinsgoodman** [comment]
@momer, we just released version 2.0.0 with your changes. Thanks for your help!

**Comment by momer** [comment]
Dope!

**Pull request merged**
